import "../sass/map.scss";
import tplHeader from "../component/header.html";
import tplFooter from "../component/footer.html";
import tplSearch from "../component/search.html";
import $ from "./query";
let header = $("#header")[0];
let footer = $("#footer")[0];
let search = $("#search")[0];
header.innerHTML = tplHeader;
footer.innerHTML = tplFooter;
search.innerHTML = tplSearch;