import "../sass/nearby.scss";
import tplHeader from "../component/header.html";
import tplFooter from "../component/footer.html";
import tplNavbar from "../component/navbar.html";
import $ from "./query";
import {circleWidth, circleHeight} from "./circle";
let header = $("#header")[0];
let footer = $("#footer")[0];
let navBar = $("#navBar")[0];
header.innerHTML = tplHeader;
footer.innerHTML = tplFooter;
navBar.innerHTML = tplNavbar;
circleHeight($(".circle"), $("#circle-wrap")[0]);